### PR TITLE
Initiate a Shared Library

### LINKED ISSUE #1: Extract shared code to a separate library
We will probably share helper code (e.g., imdb id validation) across a number of services, so a kind of common library that we can import would be very useful. What do you think?

### PR DESCRIPTION
**Pull request by rschlaefli**
### Description

This PR sets up an initial version of a shared NPM package/library.
The library code gets built and pushed to our Github Package Registry, from which we can then install it using NPM.

### Related Issues

Closes #1 

### Checklist

- [x] Have you added tests where necessary? Do all the test pass? 
- [x] Have you added descriptive comments to your code?
- [x] Have you updated the documentation related to this propo

### CODE REVIEW

**Review by nikzaugg — COMMENTED** [review]
Looks good. Thanks.

Just one question: I see that we run test in the workflow, but only on `release`, right?. Shouldn't we make them run with every change?

**Comment by rschlaefli** [comment]
@nikzaugg yep, totally missed that! thanks for the review!

**Comment by rschlaefli** [comment]
> Looks good. Thanks.
> 
> Just one question: I see that we run test in the workflow, but only on `release`, right?. Shouldn't we make them run with every change?

@nikzaugg Adapted the code to test on every `push`, but publish only on `release/created` events

**Review by nikzaugg — APPROVED** [review]
Nice, thanks.

**Pull request merged**
